### PR TITLE
Replace Network Image

### LINKED ISSUE #4: Replace network image
## Details
- Take `mlsa-logo.png` from https://drive.google.com/file/d/1Zlnne3-B7KuVtB_9mxFQuhwCSXcohnzk/view?usp=sharing
- Put the image in `assets/images/` directory.
- Replace the network image with the asset image in `spash_screen.dart`

### PR DESCRIPTION
**Pull request by Takane42**
- [x] Closes #4 
---

## PR description

im changing the network image to asset. Im sorry if i did something wrong... this is my first time coding in dart file

### CODE REVIEW

**Comment by harshtaliwal30** [comment]
Okay, everything looks good but you haven't star the repository.

**Comment by Takane42** [comment]
Done

**Comment by harshtaliwal30** [comment]
No issues @Takane42 thanks.

**Comment by Takane42** [comment]
Sure no problem

**Pull request merged**
