### PR TITLE
Created UI for Contributors Screen

### LINKED ISSUE #22: Contributors screen UI
#### Explanation
- Create UI according to the screenshot attached in the file `contributors_screen.dart`.
- Use the same background color gradient as used in `team_screen.dart`.

#### UI Attached
Frame 2

### PR DESCRIPTION
**Pull request by Mastersam07**
contributors screen

 - [x] Closes #22 
---

## PR description

- Changed the Contributor Screen UI
- Adopted Model for MemberDetails
- Created custom ContributorDetails widget

Screenshot_2021-10-05-14-42-14-004_com example mlsa_amu

### CODE REVIEW

**Comment by harshtaliwal30** [comment]
You have used the same symbol in your commit message as well. So you need to remove it from that also.

**Comment by Mastersam07** [comment]
Oh, I understand now. Will attend to that.

**Comment by Mastersam07** [comment]
> You have used the same symbol in your commit message as well. So you need to remove it from that also.

@harshtaliwal30 corrected now.

**Comment by harshtaliwal30** [comment]
Remove appbar code we have opened a separate issue for this and also star the repository according to contribution guidelines. Otherwise, everything looks good

**Comment by harshtaliwal30** [comment]
@Mastersam07 what is the update?

**Pull request closed without merging**
