### PR TITLE
[#15] Enhancement in events screen app bar

### LINKED ISSUE #15: Enhancement in events screen app bar
#### Explain in detail
- Use the AppBar widget instead of the row widget which means replace all static code with dynamic including using media queries.
- Appbar background should be transparent and the gradient should apply to the whole screen.

### PR DESCRIPTION
**Pull request by pri1311**
- [x] Closes #15 

## PR description

- Replaced row widget with AppBar widget.
- Extended gradient throughout the screen.
- Attached below is the screenshot reflecting the changes made.
WhatsApp Image 2021-10-02 at 21 25 52

### CODE REVIEW

**Comment by pri1311** [comment]
Follow-up question -- is the back button required? Or should it be removed?

**Review by harshtaliwal30 — CHANGES_REQUESTED** [review]
Following changes need to be done:

- Use the same color gradient as used in `team_screen.dart`.
- Remove extendBodyBehindAppBar property.
- Remove toolbarHeight used in AppBar.
- Remove fontsize and fontWeight property from appBar title style.

**Comment by harshtaliwal30** [comment]
Keep the back button as it is.

**Comment by harshtaliwal30** [comment]
Please attach the latest screenshot

**Comment by pri1311** [comment]
> Please attach the latest screenshot

WhatsApp Image 2021-10-02 at 22 17 41

**Comment by harshtaliwal30** [comment]
Okay merging your pull request, but according to contribution guidelines, you haven't star the repository.

**Pull request merged**
