### PR TITLE
Added Event-Details-Screen

### LINKED ISSUE #31: Event Detail Screen
#### Explain in detail
- This screen will be pushed on clicking to the event card in `events_screen.dart`.
- File name should be `event_details_screen.dart`.
- Background Color Code `#424368`.
- The down arrow icon represents the expansion of the tile.

##### Create UI according to the screenshot attached below:
event_detail

### PR DESCRIPTION
**Pull request by Shash0501**
- [ ] Closes #31 
---

## PR description
Added the Event Detail Screen

**Extra Feature**
> Added controller to Expansion Tile so the tile is visible when opened irrespective of its position.

**ScreenShots**

 image

 image

 image

### CODE REVIEW

**Review by vidita-bit — CHANGES_REQUESTED** [review]
@Shash0501 things look good but in expansion tile you have manually written code for all 3 expansion tiles instead use builder or mapping , avoid code repetition. 
- MedaiQuery at many lines is not using SizeConfig class , do not declare separate mediaquery use from sizeconfig file.

**Comment by Shash0501** [comment]
@vidita-bit 
I have **fixed** these issues
1. Replaced MediaQuery with SizedConfig.
2. Used **builder** in the **Expansion Panel**.

**Review by vidita-bit — CHANGES_REQUESTED** [review]
- You also need to apply builder/map on expansion tile which means one code for all three expansion tiles (Organizers,Winners,Sponsors).

**Comment by Shash0501** [comment]
@vidita-bit I have created the builder functions to create expansion panels in the event-detail-page .

**Review by vidita-bit — APPROVED** [review]

**Comment by vidita-bit** [comment]
> @vidita-bit I have created the builder functions to create expansion panels in the event-detail-page .

Sorry for delay @Shash0501 , now PR seems good.

**Comment by Shash0501** [comment]
@vidita-bit Ma'am, thank you for accepting the PR
I would be glad to work on more issues and contribute.

**Comment by vidita-bit** [comment]
> @vidita-bit Ma'am, thank you for accepting the PR I would be glad to work on more issues and contribute.

Okay great , but even after contributing 3-4 Pull Request you haven't starred the repository as mentioned in `README.md`.

**Comment by Shash0501** [comment]
> > @vidita-bit Ma'am, thank you for accepting the PR I would be glad to work on more issues and contribute.
> 
> Okay great , but even after contributing 3-4 Pull Request you haven't starred the repository as mentioned in `README.md`.

@vidita-bit Ma'am I have starred the repository.
I hadn't noticed that part in `README.md`.

**Pull request merged**
