### PR TITLE
Contact Us Screen

### LINKED ISSUE #43: Contact Us Screen
#### Explain in detail
- Create UI of the contact us screen as given in screen shot attached.
- File name should be `contact_screen.dart`.
- Color gradients should be same as used in other project files.
- Social media icons should have url launcher implementation

Frame 10
.

### PR DESCRIPTION
**Pull request by Pakeetharan**
- [x] Closes #43

## PR description

Contact UI Screen has been created
Url_Launcher has been implemented

Note: SizeConfig created inside the lib doesn't seem to be working from my side, so used the MediaQuery for responsive sizes. Feel free to assign someone to fix the SizeConfig.

## TODO
Add EMail and LinkedIn links
Fix the Method for Feedback Submit Method

## Screenshot
Screenshot_20211020-214136

### CODE REVIEW

**Review by vidita-bit — CHANGES_REQUESTED** [review]
- Why are so many files added in android folder ?
- Why is this  permission added in  `android/app/src/main/AndroidManifest.xml` ?

#### Following Changes need to be done:
- Use icons from `font_awesome_icon` dependency of Github  and Linkedin instead of using separate images.
-  Mediaquery needs to be done from the `sizeconfig` file only , one file of the project can't have different rules for mediaquery.
- Remove the hard coded fontsize use mediaquery.

**Comment by Pakeetharan** [comment]
<br/>

This is what I get when I use SizeConfig

- Some Files must have been from the VS Code Build
- The Permission is added to use the Url_Launcher

**Comment by vidita-bit** [comment]
> 
> 
> This is what I get when I use SizeConfig
> 
> * Some Files must have been from the VS Code Build
> * The Permission is added to use the Url_Launcher

-  Remove that permission because url_launcher does not require it.
-  Project in Vs code works fine without these files , so remove these unnecessary files.
-  Attach the screenshot of the code how you are using the sizeconfig, also check implementation of sizeconfig in other files.

**Comment by Pakeetharan** [comment]
**Here is the comparison Use of SizeConfig and MediaQuery (Directly)**

## MediaQuery Code


## MediaQuery Results


## SizeConfig Code


## SizeConfig Results


What's been wrong in here? @vidita-bit

**Comment by vidita-bit** [comment]
- Do the rest of the changes as mentioned above.
- For some reasons the `initOnStartUp` function of `size_config.dart` file called in  splash screen is not working in your local, so check it once.

**Comment by Pakeetharan** [comment]
I kinda fixed it from Local SizeConfig Initiation

## Using FontAwesomIcon


## Using Custom Image


Which one should I go with? @vidita-bit

**Comment by Pakeetharan** [comment]
All Unwanted files are removed and just waiting for your opinion to finalize

image

It's being created automatically even after manual deletion

**Comment by vidita-bit** [comment]
> * Do the rest of the changes as mentioned above.
> * For some reasons the `initOnStartUp` function of `size_config.dart` file called in  splash screen is not working in your local, so check it once.



> I kinda fixed it from Local SizeConfig Initiation
> 
> ## Using FontAwesomIcon
> 
> 
> ## Using Custom Image
> 
> 
> Which one should I go with? @vidita-bit

- For mail icon use image and for rest two (Linkedin, Github) do it with dependency only.
- Rest everything now seems good .

**Comment by Pakeetharan** [comment]
The Changes are done, Kindly check @vidita-bit

**Review by vidita-bit — APPROVED** [review]

**Pull request merged**
