### PR TITLE
Created UI for TeamScreen

### LINKED ISSUE #12: Team Screen UI
#### Explanation in detail
- Create UI according to the screenshot attached.
- Github and Linkedin are icons buttons, not images.

#### UI attached
Frame 7

### PR DESCRIPTION
**Pull request by Shash0501**
- [x] Closes #12
---

## PR description

1. Changed the Team Screen UI
2. Created Model for MemberDetails
3. Created a widget/models folder clean architecture
4. Add the functionality to launch GitHub/LinkedIn URL in the browser from the app
 
### UI screen
image

### Architecture
image

### CODE REVIEW

**Review by harshtaliwal30 — CHANGES_REQUESTED** [review]
@Shash0501 the work is nice but it needs some changes.

The following parts need small modifications.
- Remove unnecessary space from `android/app/src/main/AndroidManifest.xml`
- Use the same gradients as used in `home_screen.dart`.
- Format `team_screen.dart` file properly.
- Changes in `lib/widgets/member_details_card.dart`.
  - Do not fix the height and width of the Image, use media query.
  - Use media query in padding as well.
  - Use padding instead of sizedbox.

**Comment by Shash0501** [comment]
@harshtaliwal30 Sir, please elaborate on what you meant by **Format `team_screen.dart` file correctly**.

**Comment by harshtaliwal30** [comment]
In line 33 of `team_screen.dart`, clear up the cluster of the brackets by including commas and then use the format document.

**Comment by Shash0501** [comment]
> In line 33 of `team_screen.dart`, clear up the cluster of the brackets by including commas and then use the format document.

@harshtaliwal30 I have made the above changes.

**Review by harshtaliwal30 — CHANGES_REQUESTED** [review]
Remove unnecessary changes in `android/app/src/main/AndroidManifest.xml`.
Use media query in padding in line 14 and 22 in `lib/widgets/member_details_card.dart`

**Comment by Shash0501** [comment]
> Remove unnecessary changes in `android/app/src/main/AndroidManifest.xml`. Use media query in padding in line 14 and 22 in `lib/widgets/member_details_card.dart`

@harshtaliwal30 Sir, I made the changes you requested 
Sorry for so many iterations. I will be careful next time.

**Review by harshtaliwal30 — APPROVED** [review]
Now everything looks good. Merging your pull request.

**Pull request merged**
