### PR TITLE
appbar ui added

### PR DESCRIPTION
**Pull request by rutuja1121**
- [ ] Closes #xxxx
---
## PR description

AppBar UI added

### CODE REVIEW

**Review by vidita-bit — CHANGES_REQUESTED** [review]
- Use color codes mentioned in the issue in hex form , rest is good.

**Comment by rutuja1121** [comment]
Yes sure!

**Comment by vidita-bit** [comment]
> Yes sure!

Also take the latest pull from main branch.

**Comment by vidita-bit** [comment]
> * Use color codes mentioned in the issue in hex form , rest is good.

Update @rutuja1121 ?

**Comment by vidita-bit** [comment]
> > * Use color codes mentioned in the issue in hex form , rest is good.
> 
> Update @rutuja1121 ?

Will transfer  the issue in few hours , you may tell if facing any problem.

**Comment by rutuja1121** [comment]
Sorry for late reply..I'll do it today

**Comment by rutuja1121** [comment]
I have done the changes could you please check

**Review by vidita-bit — CHANGES_REQUESTED** [review]
Your Pull Request has merge conflicts , take the latest pull and resolve them.

**Comment by vidita-bit** [comment]
Also mention issue in your Pull Request :
Remove #xxxx and mention #[Issue Number]

**Comment by vidita-bit** [comment]
There has been lot of delay in the issue , so i am transferring the issue to carry forward the further work.

**Pull request closed without merging**
